#!/usr/bin/env python3
"""
Example: Play a savellysKone3 Song using SimpleSampler

This demonstrates how to use the sampler_player module to play
compositions generated by savellysKone3.
"""

import sys
import os

# Add parent directory to path to import savellysKone3
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:
    import savellysKone3 as sk3
except ImportError:
    print("Error: savellysKone3.py not found in parent directory")
    sys.exit(1)

from sampler_player import SimpleSamplerPlayer

def create_example_song():
    """Create a simple example song"""
    
    # Define grammars
    pitch_grammar = """
$S -> $phrase01 $phrase02
$phrase01 -> $note01 $note02 $note03 $note04
$phrase02 -> $note05 $note06 $note07 $note08
$note01 -> 60
$note02 -> 62
$note03 -> 64
$note04 -> 65
$note05 -> 67
$note06 -> 69
$note07 -> 71
$note08 -> 72
"""
    
    duration_grammar = """
$S -> $D1 $D2 $D3 $D4 $D5 $D6 $D7 $D8
$D1 -> 1.0
$D2 -> 0.5
$D3 -> 1.0
$D4 -> 0.5
$D5 -> 1.0
$D6 -> 0.75
$D7 -> 0.5
$D8 -> 0.25
"""
    
    velocity_grammar = """
$S -> $V1 $V2 $V3 $V4 $V5 $V6 $V7 $V8
$V1 -> 60
$V2 -> 80
$V3 -> 100
$V4 -> 90
$V5 -> 70
$V6 -> 95
$V7 -> 85
$V8 -> 110
"""
    
    # Create generators
    pitch_gen = sk3.ListGenerator(pitch_grammar, 8, "pitch")
    duration_gen = sk3.ListGenerator(duration_grammar, 8, "duration")
    velocity_gen = sk3.ListGenerator(velocity_grammar, 8, "velocity")
    
    # Create song
    song = sk3.Song(
        pitch_generator=pitch_gen,
        duration_generator=duration_gen,
        velocity_generator=velocity_gen,
        num_bars=4,
        ioi=1.0,
        name="ExampleSong"
    )
    
    # Generate the bars
    song.make_bar_list()
    
    # Optional: Apply some modulation
    song.modulate_pitch_with_sin(freq=0.5, amp=3.0)
    song.modulate_velocity_with_sin(freq=1.0, amp=15.0)
    
    return song


def main():
    print("=" * 60)
    print("SimpleSampler + savellysKone3 Integration Demo")
    print("=" * 60)
    print()
    
    # Create the song
    print("Creating example song...")
    song = create_example_song()
    print(f"✓ Song created with {len(song.bar_list)} bars")
    print()
    
    # Initialize sampler player
    print("Initializing SimpleSampler...")
    player = SimpleSamplerPlayer()
    
    if not player.is_available():
        print("✗ SimpleSampler not found!")
        print(f"  Expected location: {player.sampler_path}")
        print()
        print("Please build SimpleSampler first:")
        print("  cd build")
        print("  cmake .. && make")
        sys.exit(1)
    
    print(f"✓ SimpleSampler found at: {player.sampler_path}")
    print()
    
    # Play the song
    print("Playing song with SimpleSampler...")
    print("(Press Ctrl+C to stop)")
    print()
    
    try:
        temp_path, process = player.play_from_song(song, background=False)
        print()
        print("✓ Playback completed")
        
        # Clean up temp file
        os.unlink(temp_path)
        print("✓ Cleaned up temporary MIDI file")
        
    except KeyboardInterrupt:
        print("\n\n✓ Playback interrupted by user")
        player.stop()
    except Exception as e:
        print(f"\n✗ Error during playback: {e}")
        sys.exit(1)
    
    print()
    print("=" * 60)
    print("Demo complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
